const PRESENTATIONS = [
  { num:'R2-001', bp_id:4, client_name:'Lotchi',              client_website_url:'https://lotchi.live',          claap_url:'https://app.claap.io/lotchi-r1-debrief',          pre_audit_url:'https://docs.google.com/document/d/lotchi-preaudit', canva_url:'/presentations/lotchi.html', active_levers:['SEO','CRO'],                         pricing:'8 000 €',   date_r1:'2026-03-18', date_r2:'2026-04-02', status:'terminee',  current_step:4, context_entreprise:'Lotchi est une plateforme de live shopping B2C lancee en 2024. Elle permet aux marques de vendre en direct via des sessions video interactives, ciblant principalement les 18-35 ans en France et en Belgique. Le modele economique repose sur une commission sur les ventes realisees pendant les lives.', context_enjeux:'Augmenter la visibilite organique pour reduire la dependance aux paid ads et ameliorer le taux de conversion des visiteurs en participants aux lives. Objectif : tripler le trafic organique en 6 mois.', context_challenges:'Concurrence forte sur le live commerce avec des acteurs comme Livescale et Bambuser. Le SEO du site est quasi inexistant et le parcours de conversion entre la landing page et l inscription au live comporte trop d etapes.', created_at:'2026-03-15T10:30:00Z' },
  { num:'R2-002', bp_id:4, client_name:'La Tribu Happy Kids', client_website_url:'https://latribuhappykids.fr',  claap_url:'https://app.claap.io/tribu-happy-kids-r1',        pre_audit_url:'https://docs.google.com/document/d/tribu-preaudit',  canva_url:'/presentations/la-tribu-happy-kids.html', active_levers:['SEO','Google Ads','Meta Ads','CRO'], pricing:'102 000 €', date_r1:'2026-02-25', date_r2:'2026-03-12', status:'terminee',  current_step:4, context_entreprise:'La Tribu Happy Kids est une marque francaise de vetements pour enfants de 0 a 12 ans, positionnee premium avec un engagement fort sur le made in Europe et les matieres bio. CA 2025 : 2.4M EUR, 80% en ligne. La marque a une communaute Instagram active de 45K abonnes.', context_enjeux:'Passer de 2.4M a 4M de CA en ligne en 12 mois via une strategie d acquisition multi-canal. Objectif ROAS global : 5x. Reduire le CPA de 28 EUR a 18 EUR.', context_challenges:'Marche du vetement enfant tres concurrentiel avec des pure players agressifs (Petit Bateau, Jacadi en ligne). Budget marketing limite a 8.5K/mois tous canaux confondus. Saisonnalite forte avec pics en septembre et decembre.', created_at:'2026-02-19T08:17:00Z' },
  { num:'R2-004', bp_id:4, client_name:'Star Aid',            client_website_url:'https://staraid.fr',           claap_url:'https://app.claap.io/staraid-r1-call',            pre_audit_url:'https://docs.google.com/document/d/staraid-preaudit', canva_url:'/presentations/star-aid.html', active_levers:['SEO','Google Ads','LinkedIn Ads'],   pricing:'189 000 €', date_r1:'2026-02-18', date_r2:'2026-03-04', status:'en_cours',  current_step:4, context_entreprise:'Star Aid est un editeur SaaS B2B specialise dans les solutions de QVT (Qualite de Vie au Travail) et de gestion RH. Leurs produits couvrent les enquetes de satisfaction, le suivi du bien-etre et les tableaux de bord RH. 120 clients grands comptes dont Sodexo et Bouygues.', context_enjeux:'Generer 40 leads qualifies par mois via le digital pour alimenter une equipe de 6 commerciaux. Penetrer le mid-market (ETI 500-2000 salaries) en complement du grand compte historique.', context_challenges:'Acteurs historiques bien implantes (Workday, SAP SuccessFactors) avec des budgets marketing 10x superieurs. Le cycle de vente moyen est de 4 mois, ce qui rend le tracking d attribution complexe.', created_at:'2026-02-13T06:15:00Z' },
  { num:'R2-005', bp_id:1, client_name:'Coface',              client_website_url:'https://coface.com',           claap_url:'https://app.claap.io/coface-r1-kickoff',          pre_audit_url:'https://docs.google.com/document/d/coface-preaudit', canva_url:'/presentations/coface.html', active_levers:['Google Ads','Meta Ads'],              pricing:'26 500 €',  date_r1:'2026-01-22', date_r2:'2026-02-05', status:'terminee',  current_step:4, context_entreprise:'Coface est un leader mondial de l assurance-credit et de la gestion des risques commerciaux, cote en bourse (Euronext). Present dans 100 pays, le groupe accompagne 100K entreprises dans la securisation de leurs transactions B2B. CA 2025 : 1.87Md EUR.', context_enjeux:'Developper l acquisition paid sur les marches France, Allemagne et Espagne pour les produits PME (Easy Coface). Objectif : 200 demandes de devis/mois via digital, contre 80 actuellement.', context_challenges:'Les cycles de vente sont longs en B2B assurance (2-6 mois). La marque est tres connue en grand compte mais peu visible aupres des PME. Le CPC sur les mots-cles assurance-credit est tres eleve (8-15 EUR).', created_at:'2026-01-16T15:25:00Z' },
  { num:'R2-006', bp_id:1, client_name:'Join',                client_website_url:'https://join.com',             claap_url:'https://app.claap.io/join-r1-debrief',            pre_audit_url:'https://docs.google.com/document/d/join-preaudit',   canva_url:'/presentations/join.html', active_levers:['SEO','CRO'],                         pricing:'6 000 €',   date_r1:'2026-02-12', date_r2:'2026-02-25', status:'terminee',  current_step:4, context_entreprise:'Join est une plateforme de recrutement gratuite pour les PME, lancee en Allemagne et presente dans 6 pays europeens. Le modele freemium permet aux entreprises de publier des offres gratuitement avec des options premium (boost, multiposting). 80K entreprises utilisatrices.', context_enjeux:'Augmenter le trafic organique sur le marche francais de 40% en 6 mois et ameliorer le taux de conversion visiteur-inscription de 2.1% a 3.5%.', context_challenges:'Concurrence frontale de Welcome to the Jungle qui domine le SEO recrutement en France. Le site a des problemes techniques SEO (temps de chargement, pages dupliquees entre les locales).', created_at:'2026-02-09T19:02:00Z' },
  { num:'R2-007', bp_id:1, client_name:'Cafeyn',              client_website_url:'https://cafeyn.co',            claap_url:'https://app.claap.io/cafeyn-r1-strategy',         pre_audit_url:'https://docs.google.com/document/d/cafeyn-preaudit', canva_url:'/presentations/cafeyn.html', active_levers:['Google Ads','LinkedIn Ads','CRO'],   pricing:'20 000 €',  date_r1:'2026-03-27', date_r2:'2026-04-10', status:'en_cours',  current_step:4, context_entreprise:'Cafeyn (ex-LeKiosk) est une plateforme de presse digitale illimitee disponible en B2C (abonnement 9.99/mois) et B2B (offre corporate pour les CE et entreprises). 2M d utilisateurs actifs, partenariats avec Orange et la SNCF. Catalogue de 3000+ titres.', context_enjeux:'Developper l acquisition B2B via LinkedIn Ads et Google Ads pour vendre l offre corporate aux DRH et responsables CE. Objectif : 25 demos/mois a un CPA < 150 EUR.', context_challenges:'Concurrence de Readly (racheté par Bonnier) qui a plus de budget marketing. La notoriete de la marque Cafeyn reste faible aupres des decideurs B2B. Le parcours de demande de demo est trop complexe (5 etapes).', created_at:'2026-03-23T11:53:00Z' },
  { num:'R2-008', bp_id:2, client_name:'Eleven VMS',          client_website_url:'https://elevenvms.com',        claap_url:'https://app.claap.io/eleven-vms-r1-intro',        pre_audit_url:'https://docs.google.com/document/d/eleven-preaudit', canva_url:'/presentations/eleven-vms.html', active_levers:['SEO','GEO'],                         pricing:'4 500 €',   date_r1:'2026-03-30', date_r2:'2026-04-14', status:'brouillon', current_step:4, context_entreprise:'Eleven VMS est un editeur SaaS francais de Vendor Management System, specialise dans la gestion des travailleurs externes (freelances, interimaires, prestataires). La solution couvre le sourcing, l onboarding, le suivi des missions et la facturation. 40 clients mid-market et grands comptes.', context_enjeux:'Developper la visibilite organique (SEO classique) et la presence dans les reponses des IA generatives (GEO) pour capter les recherches des Directeurs Achats et DRH en France.', context_challenges:'Marche domine par SAP Fieldglass et Beeline a l international. En France, la concurrence inclut Pixid et Freelance.com. Le contenu du site est tres technique et peu oriente decision-maker.', created_at:'2025-12-01T14:15:00Z' },
  { num:'R2-009', bp_id:2, client_name:'Marc Foujols',        client_website_url:'https://marcfoujols.com',      claap_url:'https://app.claap.io/marc-foujols-r1-brief',      pre_audit_url:'https://docs.google.com/document/d/foujols-preaudit', canva_url:'/presentations/marc-foujols.html', active_levers:['SEO','Google Ads','CRO'],             pricing:'11 500 €',  date_r1:'2026-03-17', date_r2:'2026-03-31', status:'terminee',  current_step:4, context_entreprise:'Marc Foujols est une agence immobiliere de prestige fondee en 1977, specialisee dans la vente et la location de biens haut de gamme a Paris (6e, 7e, 16e). Panier moyen : 1.8M EUR a la vente. 3 agences physiques et une equipe de 25 conseillers.', context_enjeux:'Renforcer la visibilite digitale pour capter les acheteurs internationaux (30% de la clientele) et moderniser l image de marque en ligne. Objectif : 15 demandes de visite qualifiees par mois via le site.', context_challenges:'Concurrence de Barnes, Daniel Feau et Engel & Volkers qui investissent massivement en SEO et Google Ads. Le site actuel a une UX datee qui ne reflète pas le positionnement premium de la marque.', created_at:'2026-03-12T09:20:00Z' },
  { num:'R2-010', bp_id:2, client_name:'Waat',                client_website_url:'https://waat.fr',              claap_url:'https://app.claap.io/waat-r1-discovery',          pre_audit_url:'https://docs.google.com/document/d/waat-preaudit',   canva_url:'/presentations/waat.html', active_levers:['SEO','Google Ads','Meta Ads'],        pricing:'64 000 €',  date_r1:'2025-11-18', date_r2:'2025-12-02', status:'terminee',  current_step:4, context_entreprise:'Waat est un installateur de bornes de recharge pour vehicules electriques, specialise dans les coproprietes et les entreprises en Ile-de-France et region lyonnaise. Plus de 2000 installations realisees depuis 2020. CA 2025 : 8M EUR, croissance de 60% par an.', context_enjeux:'Capter la demande croissante en installations de bornes en copropriete (obligation loi LOM) via SEO et paid. Objectif : 120 demandes de devis/mois, contre 75 actuellement.', context_challenges:'Concurrence forte de Zeplug (leader), Driveco et des electriciens locaux qui se positionnent sur le creneau. Le marche est en train de se commoditiser avec une pression sur les prix.', created_at:'2025-11-10T14:12:00Z' },
  { num:'R2-011', bp_id:3, client_name:'Expertimo',           client_website_url:'https://expertimo.com',        claap_url:'https://app.claap.io/expertimo-r1-kickoff',       pre_audit_url:'https://docs.google.com/document/d/expertimo-preaudit', canva_url:'/presentations/expertimo.html', active_levers:['SEO','CRO','LinkedIn Ads'],           pricing:'13 000 €',  date_r1:'2026-03-28', date_r2:'2026-04-11', status:'en_cours',  current_step:4, context_entreprise:'Expertimo est un reseau de mandataires immobiliers independants, numero 5 en France avec 1200 conseillers actifs. Le modele repose sur une remuneration attractive (jusqu a 95% des honoraires) et des outils digitaux integres (CRM, estimation, signature electronique).', context_enjeux:'Recruter 300 nouveaux mandataires par an via le digital (actuellement 180/an). Secondaire : generer des leads vendeurs pour alimenter le reseau existant.', context_challenges:'Concurrence feroce de IAD (18K mandataires), Safti (6K) et MegAgence sur le recrutement. Les candidats comparent beaucoup et le cout d acquisition d un mandataire est en hausse (de 120 EUR a 180 EUR en 2 ans).', created_at:'2026-03-25T15:21:00Z' },
];

const ANALYSES = {
  'R2-001': {
    SEO: { note_globale:6.5, lecture_business:'Le site Lotchi a une base technique correcte (Next.js, bon Core Web Vitals) mais souffre d un deficit de contenu editorial majeur. Aucune page blog, aucun contenu educatif sur le live shopping. Le maillage interne est quasi inexistant entre les pages de categories et les replays. Le potentiel de trafic organique sur les requetes "live shopping" et "acheter en direct" est sous-exploite.', sub_scores:[{nom:'Visibilite',note:5,description:'Moins de 200 mots-cles positionnes, aucun en top 3'},{nom:'Trafic',note:4.5,description:'Environ 800 sessions organiques/mois, tres faible pour le secteur'},{nom:'Contenu',note:3.5,description:'Aucun blog, pages produit avec descriptions minimales'},{nom:'Technique',note:8,description:'Next.js bien configure, bon temps de chargement, HTTPS OK'},{nom:'Autorite',note:5,description:'DR 18, quelques backlinks de medias tech FR'}] },
    CRO: { note_globale:7, lecture_business:'Le parcours de conversion entre l arrivee sur le site et l inscription a un live comporte 5 etapes (landing > catalogue > page live > inscription > confirmation email). Le taux de conversion global est de 1.8%, bien en dessous de la moyenne e-commerce (3.2%). Les pages de live manquent de preuves sociales (pas de nombre de participants, pas d avis). Le CTA principal est peu visible sur mobile.', sub_scores:[{nom:'Ergonomie',note:7.5,description:'Design moderne et aere, bonne experience mobile'},{nom:'Message',note:6,description:'Proposition de valeur claire mais pas assez differenciante vs concurrents'},{nom:'CTA',note:5.5,description:'Bouton inscription trop bas sur la page, couleur peu contrastee'},{nom:'Reassurance',note:4.5,description:'Aucun avis client, pas de logos partenaires, pas de garantie'},{nom:'Opportunites',note:8,description:'Potentiel fort sur la creation d urgence (places limitees, countdown)'}] },
  },
  'R2-002': {
    SEO: { note_globale:6, lecture_business:'Le site La Tribu Happy Kids a un bon volume de pages produit mais un contenu editorial insuffisant. Les fiches produit manquent de descriptions uniques (beaucoup de texte duplique entre les variantes). Le blog existe mais n est plus alimente depuis 6 mois. La structure de categories est claire mais les pages de categories n ont pas de contenu textuel optimise.', sub_scores:[{nom:'Visibilite',note:6.5,description:'450 mots-cles positionnes dont 12 en top 10, principalement sur la marque'},{nom:'Trafic',note:6,description:'2800 sessions organiques/mois, potentiel estime a 8000'},{nom:'Contenu',note:5,description:'Blog abandonne, fiches produit avec texte duplique entre variantes'},{nom:'Technique',note:7,description:'Shopify bien configure, bon maillage categories > produits'},{nom:'Autorite',note:6.5,description:'DR 25, backlinks de blogs parentalite et presse feminine'}] },
    'Google Ads': { note_globale:7, lecture_business:'Les campagnes Google Ads captent du trafic sur les requetes generiques ("vetement enfant bio", "marque vetement enfant") mais le Quality Score moyen est de 5/10, impacte par des landing pages generiques. Les campagnes Shopping sont bien structurees mais les titres produit ne sont pas optimises pour le CTR. Le budget est concentre sur le Search, pas de Performance Max teste.', sub_scores:[{nom:'Structure',note:7.5,description:'Bonne segmentation marque/generique/shopping, ad groups coherents'},{nom:'Mots-cles',note:6,description:'Trop de broad match sur le generique, 30% de budget gaspille'},{nom:'Annonces',note:6.5,description:'Extensions correctes mais copies generiques, pas de test A/B actif'},{nom:'Landing pages',note:5.5,description:'Renvoient vers les categories Shopify, pas de pages dediees campagnes'},{nom:'Performance',note:7,description:'ROAS 3.8x correct mais CPA a 28 EUR trop eleve vs objectif 18 EUR'}] },
    'Meta Ads': { note_globale:5.5, lecture_business:'Les campagnes Meta generent du volume de trafic mais le taux de conversion post-clic est faible (0.8% vs 1.5% benchmark mode enfant). Le ciblage par interets est trop large et les audiences lookalike montrent des signes de saturation. Les creatifs sont essentiellement des photos produit statiques, sans UGC ni video.', sub_scores:[{nom:'Strategie',note:5,description:'Pas de funnel structure, tout le budget en acquisition froide'},{nom:'Creas',note:5.5,description:'Photos produit OK mais aucun UGC, aucune video, formats statiques uniquement'},{nom:'Ciblage',note:5,description:'Interets trop larges (mode, enfants), lookalike 5% saturees'},{nom:'Budget',note:6.5,description:'Repartition 70% acquisition 30% retargeting, ratio correct'},{nom:'Performance',note:5.5,description:'CPA 32 EUR, ROAS 2.1x — en dessous de la rentabilite minimum'}] },
    CRO: { note_globale:6, lecture_business:'Le site Shopify a un design soigne mais le parcours d achat presente des frictions. Le panier moyen est de 65 EUR, en dessous de l objectif de 80 EUR. Les pages produit manquent de photos in-situ (enfants portant les vetements). La page panier n a pas de cross-sell et le checkout ne propose pas de paiement en 3x.', sub_scores:[{nom:'Ergonomie',note:7,description:'Design propre et coherent, navigation intuitive par age et categorie'},{nom:'Message',note:5.5,description:'Le positionnement premium est sous-communique, pas de storytelling marque'},{nom:'CTA',note:6,description:'Bouton ajout panier bien place mais pas de CTA secondaire (wishlist)'},{nom:'Reassurance',note:5.5,description:'Avis Trustpilot present mais pas sur les fiches produit individuelles'},{nom:'Opportunites',note:7,description:'Fort potentiel sur le cross-sell panier et le paiement fractionne'}] },
  },
  'R2-004': {
    SEO: { note_globale:5.5, lecture_business:'Le site Star Aid souffre d un contenu trop corporate et pas assez oriente recherche. Les pages solutions sont longues mais ne ciblent aucun mot-cle specifique. Il n y a pas de pages dediees par cas d usage (bien-etre au travail, enquete RPS, barometre social). Le blog publie 1 article/mois mais sans strategie de mots-cles.', sub_scores:[{nom:'Visibilite',note:5,description:'320 mots-cles positionnes, majorite sur la marque et hors top 20'},{nom:'Trafic',note:4.5,description:'1200 sessions organiques/mois, tres insuffisant pour un SaaS B2B RH'},{nom:'Contenu',note:4,description:'Pages solutions generiques, pas de contenu par persona ni par use case'},{nom:'Technique',note:7.5,description:'WordPress bien optimise, bon temps de chargement, pas de cannibalisation'},{nom:'Autorite',note:6,description:'DR 22, quelques backlinks de medias RH et de partenaires'}] },
    'Google Ads': { note_globale:6.5, lecture_business:'Les campagnes Search ciblent les bons mots-cles ("logiciel QVT", "enquete satisfaction collaborateurs") mais le Quality Score est tire vers le bas par des landing pages qui ne matchent pas l intention de recherche. Les extensions sont bien utilisees. Pas de campagne display ni de remarketing actif.', sub_scores:[{nom:'Structure',note:7,description:'Bonne segmentation par produit (QVT, RPS, barometre), brand isole'},{nom:'Mots-cles',note:6.5,description:'Mots-cles pertinents mais volumes faibles, peu d exact match'},{nom:'Annonces',note:6,description:'Copies correctes mais pas de test d angles differents (ROI vs conformite)'},{nom:'Landing pages',note:5,description:'Renvoient vers les pages produit generiques, pas de LP dediee campagne'},{nom:'Performance',note:7,description:'CPA 180 EUR correct pour du B2B SaaS mais volume insuffisant (8 leads/mois)'}] },
    'LinkedIn Ads': { note_globale:5.5, lecture_business:'Les campagnes LinkedIn Ads ciblent les DRH et Directeurs QVT avec des formats Sponsored Content. Le ciblage est pertinent mais les creatifs sont trop corporate (visuels stock, pas de chiffres concrets). Aucune strategie ABM n est en place malgre une liste de 200 comptes cibles identifies par le commercial.', sub_scores:[{nom:'Strategie',note:5,description:'Pas de funnel structure, tout le budget sur du lead gen froid'},{nom:'Creas',note:5,description:'Visuels stock generiques, pas de temoignages clients ni de data concrete'},{nom:'Ciblage',note:7,description:'Bon ciblage par fonction (DRH, QVT) et taille d entreprise (500+)'},{nom:'Budget',note:6,description:'Budget 3K/mois correct mais pas optimise entre les formats'},{nom:'Performance',note:5,description:'CPL 220 EUR trop eleve, taux de conversion MQL>SQL de 12% seulement'}] },
  },
  'R2-005': {
    'Google Ads': { note_globale:6.5, lecture_business:'Les campagnes Google Ads de Coface sur le segment PME montrent un bon CTR (4.2%) mais un taux de conversion faible sur la page de demande de devis (1.1%). Les mots-cles sont bien selectionnes ("assurance credit entreprise", "proteger creances clients") mais le Quality Score souffre de landing pages trop denses et peu orientees conversion.', sub_scores:[{nom:'Structure',note:7,description:'Segmentation par pays (FR/DE/ES) et par produit (Easy Coface, API), propre'},{nom:'Mots-cles',note:7.5,description:'Bonne selection de mots-cles intentionnistes, peu de gaspillage'},{nom:'Annonces',note:6,description:'Copies factuelles mais peu differenciantes, pas de social proof dans les extensions'},{nom:'Landing pages',note:5,description:'Pages produit denses, formulaire en 8 champs, pas de chatbot ni de devis rapide'},{nom:'Performance',note:6.5,description:'CPA 95 EUR correct pour le secteur mais volume de conversions trop faible'}] },
    'Meta Ads': { note_globale:5.5, lecture_business:'Meta Ads est utilise en complement pour cibler les dirigeants de PME mais les resultats sont mitiges. Le format lead gen (formulaire natif) genere des leads mais de faible qualite (taux de qualification 15%). Les creatifs sont trop institutionnels et ne parlent pas aux pain points concrets des dirigeants PME.', sub_scores:[{nom:'Strategie',note:5.5,description:'Lead gen natif pertinent mais pas de nurturing post-lead, tunnel trop court'},{nom:'Creas',note:5,description:'Visuels corporate Coface, pas adaptes a l audience PME qui attend du concret'},{nom:'Ciblage',note:6,description:'Ciblage par fonction OK mais audiences trop larges, pas d ABM'},{nom:'Budget',note:6.5,description:'Budget alloue coherent (25% du total paid) mais mal reparti entre les formats'},{nom:'Performance',note:5,description:'CPL 45 EUR bas mais seulement 15% qualifies, cout reel par MQL a 300 EUR'}] },
  },
  'R2-006': {
    SEO: { note_globale:6, lecture_business:'Join a un bon potentiel SEO avec un domaine ancien et une autorite correcte (DR 45) mais le site francais souffre de problemes de cannibalisation entre les pages FR et les pages DE/EN. Les pages de categories d emploi manquent de contenu unique. Le temps de chargement mobile est de 4.2s, au-dessus du seuil recommande.', sub_scores:[{nom:'Visibilite',note:6.5,description:'2100 mots-cles positionnes en France mais peu en top 3 hors marque'},{nom:'Trafic',note:6.5,description:'12K sessions organiques/mois en FR, potentiel estime a 35K'},{nom:'Contenu',note:5,description:'Pages emploi avec contenu duplique entre locales, pas de guides employeur'},{nom:'Technique',note:5.5,description:'Hreflang mal implemente, temps de chargement mobile trop lent (4.2s)'},{nom:'Autorite',note:7.5,description:'DR 45, bon profil de backlinks grace a la couverture presse europeenne'}] },
    CRO: { note_globale:7.5, lecture_business:'Le parcours d inscription employeur est relativement fluide (3 etapes) mais le taux de conversion visiteur-inscription est de 2.1%, en dessous de l objectif de 3.5%. La page d accueil manque de social proof specifique au marche francais. Le formulaire d inscription ne propose pas d option "essai gratuit" assez visible.', sub_scores:[{nom:'Ergonomie',note:8,description:'Interface claire et moderne, bonne hierarchie visuelle, mobile-first'},{nom:'Message',note:7,description:'Proposition de valeur claire (gratuit) mais pas assez differenciante vs WTTJ'},{nom:'CTA',note:7,description:'CTA principal visible mais libelle generique ("Commencer"), pas de test A/B'},{nom:'Reassurance',note:6.5,description:'Logos clients presents mais pas de temoignages ni de chiffres cles FR'},{nom:'Opportunites',note:8.5,description:'Fort potentiel sur l ajout d un chatbot et d un calculateur d economie de temps'}] },
  },
  'R2-007': {
    'Google Ads': { note_globale:6.5, lecture_business:'Les campagnes Google Ads ciblent les requetes B2B ("presse digitale entreprise", "abonnement presse CE") avec un budget modeste. Le Quality Score moyen est de 6/10, penalise par des landing pages qui melangent l offre B2C et B2B. Pas de campagne dediee par segment (CE, DRH, bibliotheques).', sub_scores:[{nom:'Structure',note:6,description:'Une seule campagne B2B, pas de segmentation par persona ou secteur'},{nom:'Mots-cles',note:7,description:'Bons mots-cles intentionnistes mais volumes faibles, peu d alternatives testees'},{nom:'Annonces',note:6,description:'Copies axees fonctionnalites, pas assez sur les benefices (engagement, bien-etre)'},{nom:'Landing pages',note:5.5,description:'Page B2B existante mais partagee avec le B2C, formulaire trop long (7 champs)'},{nom:'Performance',note:7,description:'CPA demo 130 EUR correct mais seulement 6 demos/mois generees'}] },
    'LinkedIn Ads': { note_globale:7, lecture_business:'LinkedIn est le canal le plus pertinent pour Cafeyn B2B. Les campagnes actuelles ciblent les DRH et responsables CE avec des formats Sponsored Content. Le ciblage est bien affine mais les creatifs manquent de concret (pas de chiffres d engagement, pas de temoignage client). Le budget est sous-exploite.', sub_scores:[{nom:'Strategie',note:7,description:'Bon choix de canal, funnel awareness > consideration present mais incomplet'},{nom:'Creas',note:6,description:'Visuels propres mais generiques, pas de format carrousel ni de video temoignage'},{nom:'Ciblage',note:8,description:'Excellent ciblage DRH/CE par taille d entreprise (200+), secteur et seniorite'},{nom:'Budget',note:6.5,description:'Budget 2.5K/mois, insuffisant pour couvrir les 3 audiences cibles en parallele'},{nom:'Performance',note:7.5,description:'CPL 85 EUR correct, taux MQL 28%, meilleur canal en qualite de leads'}] },
    CRO: { note_globale:5.5, lecture_business:'Le parcours de demande de demo B2B est trop complexe : 5 etapes incluant un formulaire de 8 champs, puis un email de confirmation, puis un calendly. Le taux de completion du formulaire est de seulement 22%. La page B2B manque de social proof entreprise (logos clients, chiffres d engagement).', sub_scores:[{nom:'Ergonomie',note:6,description:'Page B2B correcte mais navigation confuse entre offre B2C et B2B'},{nom:'Message',note:5,description:'Value prop B2B floue, pas de chiffres concrets sur le ROI pour les entreprises'},{nom:'CTA',note:4.5,description:'Formulaire de 8 champs avec validation stricte, pas d option calendly direct'},{nom:'Reassurance',note:5.5,description:'Quelques logos clients mais pas de temoignage ni de case study detaillee'},{nom:'Opportunites',note:7.5,description:'Potentiel enorme sur la simplification du formulaire et l ajout de Calendly inline'}] },
  },
  'R2-008': {
    SEO: { note_globale:5.5, lecture_business:'Le site Eleven VMS a un contenu tres technique oriente product managers mais pas du tout oriente decideurs (DAF, DRH, Directeurs Achats). Les pages solutions ne ciblent pas les mots-cles recherches par les acheteurs ("gestion freelances entreprise", "plateforme gestion prestataires"). Aucune page de comparaison vs concurrents.', sub_scores:[{nom:'Visibilite',note:5,description:'180 mots-cles positionnes, majorite hors top 20, aucun en top 3'},{nom:'Trafic',note:4,description:'600 sessions organiques/mois, tres insuffisant pour un SaaS B2B'},{nom:'Contenu',note:4.5,description:'Contenu technique, pas de guides acheteur, pas de comparatifs, blog sporadique'},{nom:'Technique',note:7.5,description:'Site Webflow rapide, bonne structure, pas de problemes d indexation'},{nom:'Autorite',note:5.5,description:'DR 15, peu de backlinks, aucune strategie de link building active'}] },
    GEO: { note_globale:4.5, lecture_business:'Eleven VMS est quasiment absent des reponses des IA generatives (ChatGPT, Perplexity, Claude) sur les requetes VMS et gestion de freelances. Les concurrents SAP Fieldglass et Beeline dominent les citations. Le contenu du site n est pas structure pour etre cite par les LLM (pas de definitions claires, pas de donnees factuelles, pas de FAQ structuree).', sub_scores:[{nom:'Presence IA',note:3.5,description:'Cite dans 0 reponse sur 20 requetes testees sur ChatGPT et Perplexity'},{nom:'Contenu optimise',note:4,description:'Pas de schema markup, pas de FAQ, pas de definitions citables'},{nom:'Citations',note:3,description:'Aucune mention dans les sources citees par les IA generatives'},{nom:'Autorite',note:6.5,description:'Quelques mentions dans la presse tech FR mais pas assez pour les LLM'},{nom:'Visibilite LLM',note:5,description:'Les concurrents US monopolisent les reponses, segment FR sous-represente'}] },
  },
  'R2-009': {
    SEO: { note_globale:7, lecture_business:'Le site Marc Foujols a un bon positionnement sur les requetes de marque et sur quelques requetes geo-localisees ("immobilier prestige Paris 7e"). Le contenu editorial est de qualite mais pas optimise SEO (pas de H2/H3, pas de meta descriptions uniques). Le potentiel sur les requetes "immobilier luxe Paris" est sous-exploite face a Barnes et Daniel Feau.', sub_scores:[{nom:'Visibilite',note:7.5,description:'850 mots-cles positionnes, 35 en top 10 dont les requetes de marque'},{nom:'Trafic',note:7,description:'4500 sessions organiques/mois, potentiel estime a 12K avec contenu optimise'},{nom:'Contenu',note:6,description:'Belles descriptions de biens mais pas de contenu editorial (quartiers, tendances)'},{nom:'Technique',note:7,description:'Site propre, bon maillage annonces > quartiers, mobile OK'},{nom:'Autorite',note:7.5,description:'DR 35, bons backlinks presse immobiliere et lifestyle'}] },
    'Google Ads': { note_globale:6, lecture_business:'Les campagnes Google Ads ciblent les requetes immobilieres premium mais le CPC moyen est tres eleve (12 EUR). Les annonces manquent de differenciation vs les portails (SeLoger, Bien ici). Les extensions de lieu ne sont pas activees malgre les 3 agences physiques. Pas de campagne YouTube ni Display pour le branding.', sub_scores:[{nom:'Structure',note:6.5,description:'Segmentation par arrondissement correcte mais pas de campagne par type de bien'},{nom:'Mots-cles',note:6,description:'CPC tres eleve, pas assez de long tail ("appartement 5 pieces saint germain")'},{nom:'Annonces',note:5.5,description:'Copies generiques, pas de chiffres (nb de biens, anciennete), pas de test A/B'},{nom:'Landing pages',note:5.5,description:'Renvoient vers la page d accueil, pas de LP dediee par quartier'},{nom:'Performance',note:6.5,description:'CPA demande de visite a 85 EUR, correct pour le luxe mais volume faible'}] },
    CRO: { note_globale:6.5, lecture_business:'Le site a un design elegant mais date. Le parcours de prise de contact passe par un formulaire classique sans option de rappel immediat ni de chatbot. Les fiches bien manquent de CTAs multiples (visite virtuelle, telechargement brochure). Le taux de conversion est de 1.2%, en dessous du benchmark immobilier prestige (2%).', sub_scores:[{nom:'Ergonomie',note:7,description:'Navigation intuitive par quartier et type de bien, filtres fonctionnels'},{nom:'Message',note:7,description:'Positionnement prestige bien communique, storytelling des biens de qualite'},{nom:'CTA',note:5,description:'Un seul CTA (formulaire contact), pas de visite virtuelle ni de rappel immediat'},{nom:'Reassurance',note:6.5,description:'Anciennete et reputation bien mises en avant, manque de temoignages recents'},{nom:'Opportunites',note:7.5,description:'Potentiel sur la visite virtuelle 3D, le chatbot et le booking de visite en ligne'}] },
  },
  'R2-010': {
    SEO: { note_globale:7, lecture_business:'Waat a investi en SEO avec un blog actif (2 articles/semaine) et des pages de service bien structurees par zone geographique. Le site se positionne bien sur "borne de recharge copropriete" (position 5) mais manque de contenu sur les requetes adjacentes (aide ADVENIR, devis installation borne, etc.). Le maillage interne est a renforcer.', sub_scores:[{nom:'Visibilite',note:7.5,description:'1800 mots-cles positionnes, 45 en top 10, bonne progression +30% en 6 mois'},{nom:'Trafic',note:7,description:'8500 sessions organiques/mois, tendance haussiere forte'},{nom:'Contenu',note:7,description:'Blog actif et pertinent, guides pratiques sur les aides et la reglementation'},{nom:'Technique',note:7.5,description:'WordPress optimise, bon Core Web Vitals, schema LocalBusiness en place'},{nom:'Autorite',note:6,description:'DR 28, backlinks de medias specialises mobilite et immobilier'}] },
    'Google Ads': { note_globale:7.5, lecture_business:'Les campagnes Google Ads de Waat sont bien structurees avec une segmentation copropriete/entreprise/particulier. Le ROAS est de 8x sur le segment copropriete, tire par des mots-cles tres intentionnistes. Le budget est bien reparti mais il reste du potentiel sur les campagnes locales (geo-targeting IDF et Lyon).', sub_scores:[{nom:'Structure',note:8,description:'Excellente segmentation par persona, budget dynamique entre les segments'},{nom:'Mots-cles',note:7.5,description:'Bon mix exact/phrase match, negative keywords bien gerees'},{nom:'Annonces',note:7,description:'Copies avec chiffres (2000+ installations), extensions de lieu actives'},{nom:'Landing pages',note:7,description:'LP dediees par segment avec formulaire court (4 champs) et rappel sous 2h'},{nom:'Performance',note:8,description:'ROAS 8x sur copropriete, CPA devis 35 EUR, excellent pour le secteur'}] },
    'Meta Ads': { note_globale:6, lecture_business:'Meta Ads est utilise pour cibler les syndics de copropriete et les gestionnaires d immeubles. Les resultats sont corrects mais le volume de leads reste modeste. Les creatifs sont informatifs (infographies sur les aides) mais manquent d urgence et de temoignages de coproprietes equipees.', sub_scores:[{nom:'Strategie',note:6.5,description:'Ciblage syndics et gestionnaires pertinent, retargeting site web actif'},{nom:'Creas',note:6,description:'Infographies informatives mais pas de video temoignage ni d avant/apres'},{nom:'Ciblage',note:6,description:'Audiences par poste (syndic, gestionnaire) + centres d interet immobilier'},{nom:'Budget',note:6,description:'Budget 2K/mois, suffisant pour le volume cible mais pas de scaling'},{nom:'Performance',note:6,description:'CPL 42 EUR, taux de qualification 35%, correct sans etre exceptionnel'}] },
  },
  'R2-011': {
    SEO: { note_globale:6, lecture_business:'Le site Expertimo a un bon contenu oriente recrutement de mandataires (page carriere detaillee, simulateur de revenus) mais le SEO technique est faible. Le site est lent (5.1s sur mobile), les balises title sont generiques et il y a des problemes de pages orphelines. Le potentiel sur les requetes "devenir mandataire immobilier" est sous-exploite.', sub_scores:[{nom:'Visibilite',note:6,description:'520 mots-cles positionnes, concentration sur les requetes de marque'},{nom:'Trafic',note:5.5,description:'3200 sessions organiques/mois, devrait etre a 10K+ vu la taille du reseau'},{nom:'Contenu',note:7,description:'Bon contenu recrutement et simulateur de revenus, mais pas assez de pages SEO'},{nom:'Technique',note:4.5,description:'Site lent (5.1s mobile), pages orphelines, meta descriptions manquantes'},{nom:'Autorite',note:6,description:'DR 24, quelques backlinks de portails immobiliers et de presse locale'}] },
    CRO: { note_globale:7, lecture_business:'Le parcours de candidature mandataire est bien structure (formulaire en 3 etapes avec simulateur de revenus integre) mais le taux de conversion est de 4.5%, en dessous de IAD (6.2%). La page manque de temoignages video de mandataires actuels et de preuves de revenus concrets. Le chatbot existant est configure de maniere trop generique.', sub_scores:[{nom:'Ergonomie',note:7.5,description:'Formulaire progressif, bon flow mobile, simulateur de revenus interactif'},{nom:'Message',note:7,description:'Remuneration 95% bien mise en avant, mais pas de comparaison vs concurrents'},{nom:'CTA',note:7,description:'CTA visible et attractif (Calculer mes revenus), bon taux de clic'},{nom:'Reassurance',note:5.5,description:'Quelques temoignages texte mais pas de video, pas de chiffres de reseau recents'},{nom:'Opportunites',note:8,description:'Fort potentiel sur l ajout de videos temoignages et d un webinaire de recrutement'}] },
    'LinkedIn Ads': { note_globale:5.5, lecture_business:'Les campagnes LinkedIn Ads ciblent les agents immobiliers en poste en agence traditionnelle, avec un message de recrutement. Le ciblage est pertinent mais le volume d audience est limite. Les creatifs sont trop textuels et ne montrent pas le quotidien d un mandataire Expertimo. Pas de strategie de retargeting.', sub_scores:[{nom:'Strategie',note:5,description:'Acquisition froide uniquement, pas de nurturing ni de retargeting'},{nom:'Creas',note:5,description:'Formats texte long uniquement, pas de video ni de carrousel temoignage'},{nom:'Ciblage',note:7,description:'Bon ciblage agents immobiliers par experience et zone geographique'},{nom:'Budget',note:5.5,description:'Budget 1.5K/mois insuffisant pour couvrir toute la France'},{nom:'Performance',note:5.5,description:'CPL 95 EUR, taux de candidature effective 8%, cout par recrue a 1200 EUR'}] },
  },
};

exports.seed = async function (knex) {
  await knex('sub_scores').del();
  await knex('lever_analyses').del();
  await knex('presentations').del();

  for (const p of PRESENTATIONS) {
    const [inserted] = await knex('presentations').insert({
      ...p,
      active_levers: `{${p.active_levers.map(l => `"${l}"`).join(',')}}`,
    }).returning('*');

    const analyses = ANALYSES[p.num];
    if (!analyses) continue;

    for (const [lever, data] of Object.entries(analyses)) {
      const [analysis] = await knex('lever_analyses').insert({
        presentation_id: inserted.id,
        lever,
        note_globale: data.note_globale,
        lecture_business: data.lecture_business,
      }).returning('*');

      if (data.sub_scores?.length) {
        await knex('sub_scores').insert(
          data.sub_scores.map(s => ({
            analysis_id: analysis.id,
            nom: s.nom,
            note: s.note,
            description: s.description,
          }))
        );
      }
    }
  }
};
